name: 'Update Packwiz Mods'
description: 'Update a minecraft modpack using Packwiz'
branding:
  icon: 'download'
  color: 'purple'
on:
    workflow_dispatch:
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Go environment
              uses: actions/setup-go@v3.1.0
              with:
                go-version: '1.18'
            - name: Setup Packwiz
              run: go install github.com/packwiz/packwiz@latest
            - name: Update
              run: yes | packwiz update --all
            - uses: stefanzweifel/git-auto-commit-action@v4
